export enum InterfaceOrientation {
    INTERFACE_ORIENTATION_MASK_PORTRAIT = 1,
    INTERFACE_ORIENTATION_MASK_PORTRAIT_UPSIDE_DOWN = 2,
    INTERFACE_ORIENTATION_MASK_LANDSCAPE_LEFT = 4,
    INTERFACE_ORIENTATION_MASK_LANDSCAPE_RIGHT = 8,
    INTERFACE_ORIENTATION_MASK_LANDSCAPE = 12,
    INTERFACE_ORIENTATION_MASK_ALL_BUT_UPSIDE_DOWN = 13,
    INTERFACE_ORIENTATION_MASK_ALL = 15
}