export enum UIInterfaceOrientationMask {
    INTERFACE_ORIENTATION_MASK_PORTRAIT = 2,
    INTERFACE_ORIENTATION_MASK_LANDSCAPE_LEFT = 16,
    INTERFACE_ORIENTATION_MASK_LANDSCAPE_RIGHT = 8,
    INTERFACE_ORIENTATION_MASK_PORTRAIT_UPSIDE_DOWN = 4,
    INTERFACE_ORIENTATION_MASK_LANDSCAPE = 24,
    INTERFACE_ORIENTATION_MASK_ALL = 30,
    INTERFACE_ORIENTATION_MASK_ALL_BUT_UPSIDE_DOWN = 26
}
