name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: 10.x
    - name: Install Dependencies
      run: |
        npm install
        npm install -g akamai-cli
        npm i dep
        echo "N" | akamai install purge --force
    - name: Lint
      run: make lint
    - name: Jest Unit Tests
      run: npm run test
    - name: Mocha Unit Tests
      run: make test-unit
